routes/web.php
<?php
Route::get('/','StaticPagesController@home')->name('home');
Route::get('/help','StaticPagesController@help')->name('help');
Route::get('/about','StaticPagesController@about')->name('about');

// 用户注册
Route::get('signup','UsersController@create')->name('signup');
Route::resource('users',    'UsersController');

/* 用户登录 */
Route::get('login','SessionsController@create')->name('login');
Route::post('login','SessionsController@store')->name('login');
Route::delete('logout','SessionsController@destroy')->name('logout');

/* 激活账户邮件 */
Route::get('signup/confirm/{token}', 'UsersController@confirmEmail')->name('confirm_email');

/* 邮件发送 */
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

/* 微博创建与删除 */
Route::resource('statuses','StatusesController',['only'=>['store','destroy']]);

// 关注的人 & 粉丝 列表路由
Route::get('/users/{user}/followings', 'UsersController@followings')->name('users.followings');    // 显示用户的关注人列表
Route::get('/users/{user}/followers', 'UsersController@followers')->name('users.followers');    // 显示用户的粉丝列表

// 关注表单
Route::post('/users/followers/{user}','FollowersController@store')->name('followers.store');
Route::delete('/users/followers/{user}','FollowersController@destroy')->name('followers.destroy');

resources/views/layouts/_footer.blade.php
<div class="col-md-12">
    <footer class="footer">
        <small class="slogon">
            <img src="https://dn-phphub.qbox.me/uploads/images/201612/12/1/iq7WQc2iuW.png?imageView2/1/w/34/h/34" alt="">
            <a href="">千锤百炼，方能成钢</a>
        </small>
        <nav>
            <ul>
                <li><a href="{{ route('about') }}">关于</a></li>
            </ul>
        </nav>
    </footer>
</div>

resources/views/layouts/_header.blade.php
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <div class="col-md-offset-1 col-md-10">
            <a href="/" id="logo">Weibo</a>
            <nav>
                <ul class="nav navbar-nav navbar-right">
                    @if(Auth::check())
                        <li><a href="{{ route('users.index') }}">用户列表</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                {{ Auth::user()->name }} <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ route('users.show',Auth::user()->id) }}">个人中心</a></li>
                                <li><a href="{{ route('users.edit',Auth::user()->id) }}">编辑资料</a></li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#" id="logout">
                                        <form action="{{ route('logout') }}" method="POST">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <button class="btn btn-block btn-danger" type="submit">退出</button>
                                        </form>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    @else
                        <li><a href="{{ route('help') }}">帮助</a></li>
                        <li><a href="{{ route('login') }}">登录</a></li>
                    @endif
                </ul>
            </nav>
        </div>
    </div>
</header>

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>@yield('title','Weibo') - Laravel 入门教程</title>
    <link rel="stylesheet" href="/css/app.css">
</head>
<body>

    @include('layouts._header')

    <div class="container">
        <div class="col-md-offset-1 col-md-10">
            @include('shared._messages')
            @yield('content')
            @include('layouts._footer')
        </div>
    </div>
</body>
<script src="/js/app.js"></script>
</html>