routes/web.php
<?php
Route::get('/','StaticPagesController@home')->name('home');
Route::get('/help','StaticPagesController@help')->name('help');
Route::get('/about','StaticPagesController@about')->name('about');

// 用户注册
Route::get('signup','UsersController@create')->name('signup');
Route::resource('users',    'UsersController');

/* 用户登录 */
Route::get('login','SessionsController@create')->name('login');
Route::post('login','SessionsController@store')->name('login');
Route::delete('logout','SessionsController@destroy')->name('logout');

/* 激活账户邮件 */
Route::get('signup/confirm/{token}', 'UsersController@confirmEmail')->name('confirm_email');

/* 邮件发送 */
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

/* 微博创建与删除 */
Route::resource('statuses','StatusesController',['only'=>['store','destroy']]);

// 关注的人 & 粉丝 列表路由
Route::get('/users/{user}/followings', 'UsersController@followings')->name('users.followings');    // 显示用户的关注人列表
Route::get('/users/{user}/followers', 'UsersController@followers')->name('users.followers');    // 显示用户的粉丝列表

// 关注表单
Route::post('/users/followers/{user}','FollowersController@store')->name('followers.store');
Route::delete('/users/followers/{user}','FollowersController@destroy')->name('followers.destroy');

app/Http/Controllers/StatusesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Status;
use Illuminate\Http\Request;

class StatusesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /* 创建微博 */
    public function store(Request $request)
    {
        $this->validate($request, [
            'content'       =>  'required|max:140'
        ]);

        \Auth::user()->statuses()->create([
            'content'   =>  \request('content')
        ]);

        return redirect()->back();
    }

    // 删除微博
    public function destroy(Status $status)
    {
        $this->authorize('destroy', $status);
        $status->delete();
        session()->flash('success','微博已被成功删除！');
        return redirect()->back();
    }
}

resources/views/statuses/_status.blade.php
<li id="status-{{ $status->id }}">
    <a href="{{ route('users.show', $user->id )}}">
        <img src="{{ $user->gravatar() }}" alt="{{ $user->name }}" class="gravatar"/>
    </a>

    <span class="user">
    <a href="{{ route('users.show', $user->id )}}">{{ $user->name }}</a>
    </span>

    <span class="timestamp">
    {{ $status->created_at->diffForHumans() }}
    </span>

    <span class="content">{{ $status->content }}</span>

    @can('destroy', $status)
        <form action="{{ route('statuses.destroy', $status->id) }}" method="POST">
            {{ csrf_field() }}
            {{ method_field('DELETE') }}
            <button type="submit" class="btn btn-danger status-delete-btn">删除</button>
        </form>
    @endcan
</li>